apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-06-25T00:56:02Z"
  generation: 1
  labels:
    app: httpd-deploy
  name: httpd-deploy
  namespace: default
  resourceVersion: "9273"
  uid: a67ef991-3353-4515-9139-dfee872b9e24
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-deploy
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: httpd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
